# Generated by Django 4.1.3 on 2022-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
    ]
