# Generated by Django 4.1.3 on 2022-11-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_register_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="email",
        ),
    ]
